
/**
 * 路由表管理
 */
export class RoutePath{
  static readonly  SplashPage="pages/openEye/SplashPage"
  static readonly  MainPage="pages/openEye/MainPage"
  static readonly  DetailPage="pages/openEye/commonDetail/DetailPage"
  static readonly  CategoryDetailPage="pages/openEye/categoryDetail/CategoryDetailPage"
  static readonly  TopicDetailPage="pages/openEye/topicDetail/TopicDetailPage"
  static readonly  ContainerPage="pages/openEye/container/ContainerPage"
  static readonly  TestHorizontalPage1="pages/openEye/test/TestHorizontalPage1"
  static readonly  TestHorizontalPage2="pages/openEye/test/TestHorizontalPage2"
  static readonly  CoordinatePage="pages/openEye/test/CoordinatePage"
}